### ISSUE TITLE
[All pages] Extremely long inputs error

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#10]
Tested By: Claude

Date Tested: 10-19-17 10:46 AM

Test Case Summary: Signing up with extremely long inputs

Test Case Details: Tried to sign up by placing a large amount of characters on the text fields

Steps to reproduce error

- In the Sign up Screen, the tester should enter the following details:
- ID Number: 1111111
- Last Name: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
- First Name: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
- Middle Name: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
- Colege: COB
- E-mail: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA@A.com
- Course: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
- Password: asd1234
- Password: asd1234

Expected Output: The system should block the user from entering extremely long inputs in the text fields through constranits. The user must not be allowed to sign up

Actual Output: The system tells the user that they have successfully signed up. **However the user does not show up in the database**

**Comment by roiiigibiv** [comment]
I have updated signup page. Please re-evaluate. Thanks.

**Comment by ericembestro** [comment]
I updated all the input boxes to not add more than 50 characters PER input. Please re-evaluate. Thanks
