### ISSUE TITLE
[Log out] Clicking the browser's back button bug

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#11]
![back button](https://user-images.githubusercontent.com/25079774/32180941-3c656290-bdce-11e7-9b5a-25678e177d15.gif)
Tested By: Claude

Date Tested: 10-30-17 10:05PM

Test Case Description: Logging out then clicking the back button

Test Case Details: The user was redirected to their profile when clicking the browser’s back button
Steps to reproduce error

- In the log in page, enter the following credentials:
 - E-mail: alexander_agno@dlsu.edu.ph
 - Password: alex
- After that, log out of the website
- Then, click the back button
- Then, click edit profile

Expected Output:

- The user should not be able to go back to their profile with the browser’s back button
- The cookie must not exist anymore.

Actual Output:

- The user was allowed to go back to their profile using the browser’s back button
- The cookie no longer exists
- Editing the profile resulted in a nullPointerException

**Comment by AlexAgnoII** [comment]
On the case. But I'll fix this once I'm done with my other task. It's easy to implement, but we'll have to organize the pages to make the code efficient.
