### ISSUE TITLE
[VIEW PROFILE] Personal information not displayed on the profile page

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#15]
![us5 2 1](https://user-images.githubusercontent.com/25523187/33197952-2ee7e882-d123-11e7-8730-ffb280ef076d.gif)

Test ID: 5.2.1

Tested By: Dan

Date Tested: 11/24/17
2:03pm

Test Case Description: Viewing the profile when the student just signed up

Steps to reproduce error:

- Log in using the e-mail alexander_agno@dlsu.edu.ph
- Click the Personal Information tab in the student’s profile page

Expected Output: 
The personal information tab should display the following results:

- Address: #100 Sct. Boy bata
- City: Quezon Ciity
- Province: Batangas
- Country: Philippines
- Zip Code: 1104 
- Mobile Number: 09178364730
- Telephone Number: 7024242
- Birthday: 12/03/1997
- Age: 19
- Gender: Male
- Civil Status: Single
- Nationality: Filipino

Actual Output: 
The personal information tab displayed none/the following results:

- Address: 
- City: 
- Province: 
- Country: 
- Zip Code: 
- Mobile Number: 
- Telephone Number: 
- Birthday: 
- Age: 
- Gender: 
- Civil Status: 
- Nationality:

**Comment by AlexAgnoII** [comment]
Bug fixed!
