### ISSUE TITLE
[Sign up] There is still no hint for the password policy/Some bugs with the password policy

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#22]
![password policy](https://user-images.githubusercontent.com/25079774/33517355-f324eac4-d7bd-11e7-8de3-f4a9ca7c21fd.gif)

Test ID: 2.3.3

Tested By: Claude

Date Tested: 12-03-2017
12:04 AM

Test Case Description: Testing the password constraint

Steps to reproduce error
On the sign-up page, the user must enter the following inputs for the password text box

- Claude1,
- Trump1,
- Claude1!
- Trump1!

Expected Output:
All passwords should be valid and no error message should pop up

Actual Output:
The following passwords had an error:

- Claude1,
- Trump1,

The following passwords had no error:

- Claude1!
- Trump1!

**The password error message is also not clear, since it does not indicate that there should be a number in the password**
**There was also no hint on the page on what the password policy should be**

Suggested Fix
![password hint](https://user-images.githubusercontent.com/25079774/33517351-e2713d40-d7bd-11e7-8dae-d1dc7f067a5d.png)
Summary of the picture: Make a hint button near the password field that explains the password policy to the user

**Comment by claudesedillo** [comment]
UPDATE: I tested the constraints again with the following inputs

- Claude1! - 8 characters (valid)
- Claude1, - 8 characters (valid)
- Trump1! - 7 characters (invalid)
- Trump1, - 7 characters (invalid)
- Truncate1! - 10 characters (valid)
- Truncate1, - 10 characters (valid)

![password policy 2](https://user-images.githubusercontent.com/25079774/33517792-65e17dbe-d7c5-11e7-8157-4832a2ca714b.gif)

![password policy 2](https://user-images.githubusercontent.com/25079774/33517800-79cc106e-d7c5-11e7-962c-06cb7e64c3b9.PNG)

It turns out that in line 193 of Signup.js, the special character checker does not include the comma (,) and period (.) which are sometimes used for passwords that need a special character. Should we just include these 2 in the code or find a way for the script to check for virtually all special characters? @AlexAgnoII 

As for the front end, the situation is still the same @ericembestro

**Comment by ericembestro** [comment]
Please re-evaluate this. Thanks

**Comment by claudesedillo** [comment]
The analyst side is solved here. We're still discussing what to do with the dev side
