### ISSUE TITLE
[Edit Profile] Accumulation

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#23]
Question: Why can't I click on edit?
![accumulation](https://user-images.githubusercontent.com/25079774/33517932-acd613c2-d7c7-11e7-83b8-31e2d3e3034e.gif)

Regardless, placing a hint on this field is **NECESSARY**. Because accumulation is sensitive and can be confusing for the user. Here's a suggestion
![accumulation](https://user-images.githubusercontent.com/25079774/33517968-55423874-d7c8-11e7-929a-c3f38ab0ce2b.PNG)

**Comment by ericembestro** [comment]
Can you check this again if this issue has been resolved?

**Comment by ericembestro** [comment]
Added tooltips. Please re-evaluate. Thanks
