### ISSUE TITLE
[Sign up] Accumulated UX Problems

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#24]
Tested By: Claude 12-03-2017 1:30AM

UX Problem 1: Signing up with an empty college and no error message
![empty college but tabbed to it](https://user-images.githubusercontent.com/25079774/33518153-4f7d9200-d7cb-11e7-9d96-f579a3afc936.gif)

UX Problem 2: Signing up with an empty college, entering an invalid middle name, removing it, then signing up
![empty college and middle name bug](https://user-images.githubusercontent.com/25079774/33518158-63c63672-d7cb-11e7-8c7d-32a27539859a.gif)

Expected Output:

- For all test cases, none of them should be allowed to sign up
- College must be highlighted red and the user must be informed that they need to add a college
- For UX Problem 2, The error message for middle name must be removed when the invalid input was cleared

Actual Output:

- For all test cases, they were allowed to sign up even with the empty college field
- For UX Problem 2, The error message remained even if the invalid input was removed

**Comment by ericembestro** [comment]
Please reevaluate this issue with the new page. Thank you

**Comment by ericembestro** [comment]
please re-evaluate this again with regards to the Issue #38
