### ISSUE TITLE
[View Profile] Hint on what Internal/External involvements refer to

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#25]
Since the feature might be confusing to the user, adding a hint might be necessary
![involvements](https://user-images.githubusercontent.com/25079774/33518314-b4474b70-d7cd-11e7-8a87-a8e9420a757c.PNG)

**Comment by claudesedillo** [comment]
Well the image got bugged in paint, but you get the point

**Comment by ericembestro** [comment]
Added tooltips. Please re-evaluate. Thanks
