### ISSUE TITLE
[Change password] Change password not working

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#26]
![change password](https://user-images.githubusercontent.com/25079774/33522837-30b810cc-d832-11e7-8a78-9a1caaed4f37.gif)
Tested By: Claude

Date Tested:
12-03-17
1:45 PM

Test Case Description: Changing the password of a confirmed account

Steps to reproduce error
On the login page, the user must input the following:

- Email: alex@alex.com
- Password: alex

Afterwards, click the settings button
In the settings page, the user must place the following inputs

- Old password: alex
- New Password: Claude1!
- Confirm New Password: Claude1!

Expected Output:
The password should be changed because the old password is correct and the new password satisfies the password policy

Actual Output:
The password was not accepted

**Comment by Dagtwice** [comment]
![15 3 1](https://user-images.githubusercontent.com/25523187/33887495-e258a55e-df84-11e7-91b4-b7398f5a4544.gif)

Retested the issue.
Change password works but no clear prompts as to what really happened.
Back button doesn't work.

**Comment by ericembestro** [comment]
I've changed this. Please reevaluate so I can change more to this later. Thanks
