### ISSUE TITLE
[Change password] Enter button for confirming, consistency of textboxes, add a back button

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#27]
![change password](https://user-images.githubusercontent.com/25079774/33522896-8c759334-d833-11e7-9b0b-60336d2180bf.PNG)

TO DO:

- Please add an enter button listener for the "Change password" Button
- Please make the text boxes consistent in design
- Please add a back button which will redirect the user to the homepage
  - This is needed because the user is caught in a dead end when clicking the settings page
  - The button should be labeled as "back to home" or something similar, so that the user knows where the back button will lead them
  - Yes, the user can go back to the homepage using the browser's back button, but that should not be the only way for the user to navigate

UPDATE: I realized that the website's logo at the top of the page leads back to the homepage, but it's not noticeable enough.

Reference for adding a back button: https://ux.stackexchange.com/questions/74311/should-a-web-based-ui-rely-on-the-browser-back-button

**Comment by ericembestro** [comment]
Can you reevaluate this again?
