### ISSUE TITLE
[Sign Up] Duplicate inputs from an existing account/Verification prompt showing even if there are invalid inputs

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#28]
![us2 3 7](https://user-images.githubusercontent.com/25523187/33553035-11d1f5b4-d932-11e7-934d-56440c7cc4c5.gif)

**Test ID:** 2.3.7

**Tested By:** Dan

**Date Tested:** 
Dan 
12-04-2017 
8:18 PM

**Test Case Details:** Using the same inputs from an existing account.
**Steps to reproduce error:**
After signing up an account, create another account using all the same information from an existing account.
**Expected Output:**
The user shouldn’t be allowed to signup and will be prompted that the account already exists; the verification message shouldn't appear.

**Actual Output:** The user wasn’t allowed to signup but the message on verification still appeared.

**Comment by ericembestro** [comment]
Is the alert still visible?

**Comment by Dagtwice** [comment]
![5](https://user-images.githubusercontent.com/25523187/33991670-786635b2-e10a-11e7-93f2-dcef152dcad0.gif)

-Still same. 
Tested on:
12-14-2017 8:07PM

**Comment by ericembestro** [comment]
I edited the html to restrict if id num or email is already taken. Please re-evaluate. Thanks

**Comment by Dagtwice** [comment]
![9](https://user-images.githubusercontent.com/25523187/33995951-869d902a-e11a-11e7-9871-05bafd0150df.gif)

- Main issue here is the "verification" message appearing even if the inputs were all duplicated from an existing account.
-Now there's no alert showing up about the idnum and email being already taken.

Tested on: 12-14-17 10:03PM

**Comment by AlexAgnoII** [comment]
This is fixed, pls check
