### ISSUE TITLE
[Sign up] Remove alert dialogs for invalid inputs and highlight the wrong fields

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#30]
![show errors](https://user-images.githubusercontent.com/25079774/33558104-089875c4-d944-11e7-89cb-d5f108e8319c.gif)

Tested By: Claude

Date Tested: 12-04-2017
10:46 PM

Test Case Description:  Signing up with empty fields, but with an e-mail and ID Number that exists in the database to force an error

Steps to reproduce error

- On the sign-up page, the user must input the following
- IDNum: 11438878 (Exists in DB)
- E-mail: claudesedillo@gmail.com (Exists in DB)
- Click sign up

Expected Output:
The user must not be allowed to sign up because there are empty fields. The missing/empty fields must be highlighted red for the user to notice.

Actual Output:
The user was not allowed to sign up and there were no indicators of what the user is missing

Suggested Output:
![highlight errors](https://user-images.githubusercontent.com/25079774/33558511-fdf3fb60-d944-11e7-809e-3526fcfef13c.PNG)

**Comment by ericembestro** [comment]
I added the constraints. Please re-evaluate. Thanks.

**Comment by claudesedillo** [comment]
Please check issue #36 #37 #38 for the new issues. Thanks!

**Comment by ericembestro** [comment]
Can you please re-evaluate this again? Thanks
