### ISSUE TITLE
[Change Password] Text misaligned

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#32]
![this](https://user-images.githubusercontent.com/25079774/33567330-bdedcf32-d95d-11e7-816b-c365225681c9.PNG)

The "Current Password" text is misaligned

Tested on a monitor with 1366x768 resolution

**Comment by ericembestro** [comment]
Can you try this I again because I use the same resolution with this result.
![image](https://user-images.githubusercontent.com/25545156/33607296-972bdde6-d9fb-11e7-8df1-8de175037f48.png)
