### ISSUE TITLE
[Change pasword] Place proper indicators for wrong inputs/Enter listener for change password

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#33]
![password alert new](https://user-images.githubusercontent.com/25079774/33568133-6834f004-d960-11e7-8946-4ccf2398c30e.gif)

Tested By: Claude

Date Tested: 12-04-2017
10:46 PM

Test Case Description:  
Entering the correct password
Entering a new password that does not match the password policy

Steps to reproduce error

- On the login page, the user must enter the following inputs:
- E-mail: alex@alex.com
- Password: alex
- On the change password page, the user must enter the following inputs:
- Current password: alex
- New Password: asd
- Verify Password: asd

Expected Output:

- The user should not be allowed to change their password because the new password does not satisfy the new password policy
- The text fields that have an error should be highlighted so that the user would know where they entered a wrong input

Actual Output:

- The user was not allowed to change their password
- There was no proper message on what they did wong

**Comment by ericembestro** [comment]
I updated the page. Please re-evaluate again. The only problem now is the current password if current password is really your password

**Comment by ericembestro** [comment]
Please re-evaluate this again. Thanks
