### ISSUE TITLE
[Forgot Password] Clicking the logo won't redirect the user to the login page

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#35]
![change password ux prob](https://user-images.githubusercontent.com/25079774/33589971-165fc23e-d9b7-11e7-81d8-18cf5c5cecc6.gif)

Tested By: Claude
Date Tested: 12-05-2017
12:04PM

Test Case Description:  
Attempting to go back to the login page using the website’s logo on the top of the screen

Steps to reproduce error

- On the login page, click the “forgot password” link
- Try to go back to the login page using the logo on the top

Expected Output:

- The user should be redirected to the login page
- If the user gets redirected to the hompage if they are logged in, I believe it is safe to assume that they should be redirected to the login page if they are not logged in

Actual Output:

- The user was not redirected to the login page

**Comment by ericembestro** [comment]
this is for the devs since we're working with jsps. But I added homepage link in the logo
