### ISSUE TITLE
[Sign up] Remove alert dialog for duplicate id number and e-mail

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#36]
![remove dialog](https://user-images.githubusercontent.com/25079774/33698105-561e90d2-db45-11e7-8241-71c8eb48b89e.gif)

Tested By: Claude

Date Tested: 12-07-2017
11:50 AM

Test Case Description:  
Signing up with a duplicate e-mail and id number and empty college to test the new constraints

Steps to reproduce error

- On the sign-up page, the user must input the following
- IDNum: 11438878
- E-mail: claudesedillo@gmail.com
- Fill all fields except college
- Click sign up

Expected Output:

- The user must be notified that the ID number and e-mail are taken by highlighting invalid the text fields red

Actual Output:

- The user was notified that the e-mail and ID number is taken, however it was through an alert dialog

**Comment by Dagtwice** [comment]
- Retested the issue.
- Alert dialog was removed, but the verification link modal still appears thus making it unable for the user to read the prompts about duplicates.

**Comment by ericembestro** [comment]
Can this be re-evaluated again? Thanks

**Comment by AlexAgnoII** [comment]
Modal fixed, pls check. Its no longer a modal, but a new page
