### ISSUE TITLE
[Sign up] "Repeat Password" text box turning red instantly as the user clicks it

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#37]
![password error](https://user-images.githubusercontent.com/25079774/33698169-bb091c4c-db45-11e7-80cf-f887de675c84.gif)

Tested By: Claude

Date Tested: 12-07-2017
11:50 AM

Test Case Description:  
Testing the "Repeat password" Text box

Steps to reproduce error

- On the sign-up page, the user must input the following
- IDNum: 11438878
- E-mail: claudesedillo@gmail.com
- Password: Password1!
- Click the "Repeat Password" Textbox
- Re enter the password

Expected Output:

- The text box should not turn red instantly

Actual Output:

- The text box turned red instantly even if the user has not typed anything yet

**Comment by ericembestro** [comment]
I changed the behavior of the constraint. Please reevaluate. Thanks.
