### ISSUE TITLE
[Sign up] No error notification for leaving college empty

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#38]
![remove dialog](https://user-images.githubusercontent.com/25079774/33698232-28f59082-db46-11e7-8562-617ccaf0f884.gif)

Tested By: Claude

Date Tested: 12-07-2017
11:50 AM

Test Case Description:  
Signing up with a duplicate e-mail and id number and empty college to test the new constraints

Steps to reproduce error

- On the sign-up page, the user must input the following
- IDNum: 11438878
- E-mail: claudesedillo@gmail.com
- Fill all fields except college
- Click sign up

Expected Output:

- The user must be notified that they have to select a college

Actual Output:

- The user was not notified that their college was empty

**Comment by ericembestro** [comment]
Added missing constraints. please reevaluate again. Thanks

**Comment by claudesedillo** [comment]
![sign up no red on college](https://user-images.githubusercontent.com/25079774/33942362-a71ad06c-e050-11e7-88c8-61b0f5a60b63.gif)

Apparently, if only the college is empty it won't turn red.

![how to make the red appear](https://user-images.githubusercontent.com/25079774/33942430-d91a9f84-e050-11e7-815b-83866f6cb894.gif)

However, when you leave another field empty alongside college, it will turn red

**Comment by ericembestro** [comment]
Updated the JS file. Please re-evaluate. Thanks
