### ISSUE TITLE
[Change password] Alignment probs

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#39]
![ux prob](https://user-images.githubusercontent.com/25079774/33698313-9de0b2d2-db46-11e7-901c-7ee530b0e4f0.PNG)
The website logo seems to be misaligned.
does this only apply to my machine?

**Comment by ericembestro** [comment]
Can you ask other QA's to reevaluate this since on my machine it works fine. 
![image](https://user-images.githubusercontent.com/25545156/33794312-30adc82a-dd04-11e7-9450-9b9827eebcd6.png)

**Comment by ericembestro** [comment]
I made a new one. Please re-evaluate. Thanks.

**Comment by claudesedillo** [comment]
![alignment fixed](https://user-images.githubusercontent.com/25079774/33886826-caeb06c0-df82-11e7-8579-f073528f8e75.PNG)
i just checked mine again. it's fixed
