### ISSUE TITLE
[AdminSearchForStudents] College of Computer Studies not College of Computer Science

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#40]
![ccs](https://user-images.githubusercontent.com/25079774/33728001-084d525c-dbb4-11e7-9127-400cdd36d822.PNG)

Change Colllege of Computer Science to College of Computer Studies

**Comment by ericembestro** [comment]
Edited the js file. Please re-evaluate again. Thanks

**Comment by claudesedillo** [comment]
![still nothing](https://user-images.githubusercontent.com/25079774/33885646-e98c6f3c-df7e-11e7-89df-3a937fc15e11.gif)
There is still no results

Also, the actual output has changed:

- The list is always empty
- There are 3 student found even though there are no results   *new*

**Comment by claudesedillo** [comment]
![science](https://user-images.githubusercontent.com/25079774/33886231-d30463ee-df80-11e7-8377-019f2501f3ab.PNG)
it's still there
