### ISSUE TITLE
[View Profile] College of Computer Science

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#41]
![ccs 2](https://user-images.githubusercontent.com/25079774/33729273-0d4b87a2-dbb8-11e7-90bb-7736db267dee.PNG)

Change to college of computer studies

**Comment by ericembestro** [comment]
Edited the js file. Please re-evaluate again. Thanks

**Comment by claudesedillo** [comment]
![still there](https://user-images.githubusercontent.com/25079774/33884715-c0405b14-df7b-11e7-98e9-65fc5d36578a.PNG)
it's still there
