### ISSUE TITLE
[Search for students] Change "College" option to "All Colleges"

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#42]
![change to all colleges](https://user-images.githubusercontent.com/25079774/33751617-0f90df12-dc17-11e7-8fac-2be262abcc6d.gif)

Date tested: 12-08-2017, 12:55 PM

Change the "college" option to "all colleges"

**Comment by ericembestro** [comment]
should I also change the "awards" to "all awards" ?

**Comment by ericembestro** [comment]
replaced "College" to "All Colleges" plus "Award" to "All Awards". Please re-evaluate. Thanks
