### ISSUE TITLE
[Search for students] Applying new search filters does not remove the old results

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#44]
![search error](https://user-images.githubusercontent.com/25079774/33888279-8b2f2872-df87-11e7-98da-4d9bc49ad106.gif)

Tested By: Claude

Date Tested: 12-07-2017
11:50 AM

Test Case Description:  

- Filtering the search results to COB then to CED
- Steps to reproduce error
- On the login page, login as an admin
- On the search bar, click “CCS” on the college filter

Expected Output:

- Log in as admin
- Go to search page
- Apply the COB filter in the search
- Then, apply the CED filter in the search

Actual Output:

- The list of COB students was displayed on the first filter
- The list of CED students were placed on the bottom of the list of COB students

**Comment by ghost** [comment]
Fixed
