### ISSUE TITLE
[Forgot Password] Clicking the logo won't redirect the user to the login page

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#45]
![1](https://user-images.githubusercontent.com/25523187/33888373-d01be8b2-df87-11e7-8319-fe5d92b07d28.gif)

Tested By: Dan
Date Tested: 12-12-2017
9:57PM

Test Case Description:
Attempting to go back to the login page using the website’s logo on the top of the screen

Steps to reproduce error

- On the login page, click the “forgot password” link
- Try to go back to the login page using the logo on the top

Expected Output:

- The user should be redirected to the login page
- If the user gets redirected to the hompage if they are logged in, I believe it is safe to assume that they should be redirected to the login page if they are not logged in

Actual Output:

- The user was not redirected to the login page

**Comment by Dagtwice** [comment]
Back button doesn't work either.

**Comment by ericembestro** [comment]
I've modified the jsp file. Please re-evaluate. Thanks.

**Comment by Dagtwice** [comment]
![6](https://user-images.githubusercontent.com/25523187/33991741-d1282296-e10a-11e7-9974-a6fc2c0d176b.gif)

- Clicking the logo/back button is still not working.

**Comment by ericembestro** [comment]
I've edited the resetpasswordemail. Please re-evaluate again. Thanks

**Comment by Dagtwice** [comment]
Fixed! thanks
