### ISSUE TITLE
[Forgot Password] Resetting the password is unclear

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#46]
![2](https://user-images.githubusercontent.com/25523187/33889042-e160508e-df89-11e7-83e5-de360b4780bd.gif)

Tested By: Dan
Date Tested: 12-12-2017
10:06 PM

Test Case Description:
Resetting password.

Steps to reproduce error

- Reset password with all valid inputs.

Expected Output:
- The user will be prompted that it was successful.
- Password will be changed.
- The user should be redirected to the login page.

Actual Output:
- The user was prompted that something went wrong then nothing happened after.

**Comment by AlexAgnoII** [comment]
@Dagtwice @claudesedillo 
The bug happens from the DB, there's a null value in the email thus resulting to a null pointer exeption.
I'll push the latest DB with proper values
This one's fixed on the dev side

**Comment by ghost** [comment]
Fixed
