### ISSUE TITLE
[Search for Students] Logo is fixed to the top center of the screen

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#47]
![search gui error](https://user-images.githubusercontent.com/25079774/33890011-ea88b176-df8c-11e7-8389-64602363fb04.gif)

Tested By: Claude

Date Tested: Claude
12-12-17
10:27 PM

Test Case Description:  
UX Bug with the logo

Steps to reproduce error

- Log in as admin
- Go to search page
- Add college filter to make the search results longer
- Scroll down

Expected Output:

- The logo should not follow the user when scrolled down

Actual Output:

- The logo is fixed to the screen and follows the user when scrolling down

**Comment by ericembestro** [comment]
I've updated the css regarding the issue. Please re-evaluate if there are changes

**Comment by claudesedillo** [comment]
![still there](https://user-images.githubusercontent.com/25079774/33987154-d561935c-e0fa-11e7-96f0-31844876ccd1.PNG)

it's still there

**Comment by ericembestro** [comment]
I updated the css again. Please reevaluate
