### ISSUE TITLE
[Search] Search results fixed to "found 3 students" regardless of the size of the search result

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#48]
![search results](https://user-images.githubusercontent.com/25079774/33891196-2c46d630-df90-11e7-96a7-baf5dbca8f68.gif)

Tested By: Claude
Date Tested: 

- 12-12-17
- 10:47 PM

Test Case Description:  

- Searching with a filter that will result to less than 3 students

Steps to reproduce error

- Log in as admin
- Go to search page
- Enter “claude” on the text bar
- Enter “CED” on the college filter

Expected Output:

- The search result should say “found 1 student”

Actual Output:

- The search result says “found 3 students”

**Comment by ghost** [comment]
Fixed
