### ISSUE TITLE
[Edit profile info] User not redirected to the updated profile page. Incorrect derived age.

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#49]
![3](https://user-images.githubusercontent.com/25523187/33929518-b9e75d9a-e024-11e7-8295-112f9239e0dc.gif)

Tested By: Dan
Date Tested:
12-13-2017
3:21 PM

Test Case Description:
Adding valid inputs on all the fields in personal information.

Steps to reproduce error:

- Address: #15 Sample
- City: Pateros
- Province: Batangas
- Country: Philippines
- Zip Code: 1621
- Mobile Number: 09568665035
- Telephone Number:  6417453
- Birthday: 02/15/2000
- Gender: Male
- Civil Status: SIngle
- Nationality: Filipino

Expected Output:

- The user should be able to successfully add his inputs to his profile.
- The age should be derived correctly.
- The user should be redirected to his updated profile.

Actual Output:

- The user was able to update his profile information.
- The derived age was not correct.
- The user needs to manually refresh the page.

**Comment by ghost** [comment]
Fixed
