### ISSUE TITLE
[Forgot Password] Expiry of the link

### ISSUE THREAD

**Issue by carlol11** [AlexAgnoII/SOFENGG#51]
![us16 3 2](https://user-images.githubusercontent.com/32904202/33943483-3a10faf6-e054-11e7-98fd-acb6fb84fb22.gif)

QA ERROR REPORT ID 16.3.4
Test ID: 16.3.4

Tested By: Edward
Date Tested: 12-13-17
10:07 PM

Test Case Description:  

- Expiry of the link upon forgot password process was successful
- Steps to reproduce error
- Click “Forgot Password?”
- Enter Email and wait for the link to be received
- Once received, click on the link to change the password
- In the link, the user should be able to change his forgotten password
- Change password success
- Click the link again and change password again

Expected Output:

- The link should’ve been expired because the user already changed his/her password

Actual Output:

- The user was able to change his password again

**Comment by AlexAgnoII** [comment]
Fixed, pa check please
