### ISSUE TITLE
[Change password, reset password] Make the back button consistent with the sign up back button

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#57]
![bacc button 2](https://user-images.githubusercontent.com/25079774/33979166-22319ca8-e0de-11e7-8ad6-6704ad6188a2.PNG)
![bacc button](https://user-images.githubusercontent.com/25079774/33979168-2265cec4-e0de-11e7-9695-192016b85b83.PNG)

Please change the back button of these pages to look like the sign up's back button. It's because it's not that noticeable

![sign up bacc](https://user-images.githubusercontent.com/25079774/33979202-45034e16-e0de-11e7-9bac-ec2548a61efb.PNG)

Here's the sign up back button for reference

**Comment by ericembestro** [comment]
Changed for ResetPassword.jsp. Please re-evaluate. Thanks

**Comment by roiiigibiv** [comment]
Changed for ChangePassword.jsp. Please do re-evaluate. Thank you
