### ISSUE TITLE
[Add announcements] Adding announcements when the admin is already logged out in another tab

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#59]
![admin announcement log out](https://user-images.githubusercontent.com/25079774/33981103-7d2a23b6-e0e6-11e7-9d8d-b9cf3bff125a.gif)

The gif is slow and laggy on this one because it's hard to record a large part of the screen

Test ID:12.3.1
Tested By: Claude

Date Tested:
12-14-17
3:33 PM

Test Case Description:  

- Adding an announcement while logging out in another tab

Steps to reproduce error

- Log in as an admin
- Open the project in another tab
- Log out in the new tab
- Add a new announcement on the original tab

Expected Output:

- The admin should not be allowed to add a new announcement because they are already logged out

Actual Output:

- The admin was allowed to add a new announcement despite being logged out already in another tab

**Comment by ghost** [comment]
Fixed
