### ISSUE TITLE
[Verification link] Clicking the sign up verification link while someone else is logged in

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#64]
![verification link](https://user-images.githubusercontent.com/25079774/33991720-b238deac-e10a-11e7-9dab-e3a8a8407628.gif)

Test ID:3.3.2
Tested By: Claude
Date Tested:
12-14-17
4:52 PM

Test Case Description:  

- Clicking the verification link while another user is logged in 

Steps to reproduce error

- Create a new account using valid inputs
- When the e-mail is received, do not click it yet, instead, log in as another user
- Click the verification link

Expected Output:
The user should be redirected to the verified success page even if there is another user logged in

Actual Output:
The user was verified, however he was redirected to the homepage of the user logged in

**Comment by ghost** [comment]
Fixed
