### ISSUE TITLE
[View announcement] View announcement is not working.

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#66]
![10](https://user-images.githubusercontent.com/25523187/34001446-f97c3406-e12a-11e7-9a89-06ed9d91ac6c.gif)

**Test ID:** 6.3.1
**Tested By:** Dan

**Date Tested:**
12-14-17
11:53 PM
**Test Case Description:**  

- The students should be able to view all the announcements made by the admin.

**Steps to reproduce error**

- Login as a student.
- Go to “Announcements” from the menu.

**Expected Output:**

- All announcements with the title, date and time posted, and the description are listed in the page. 

HI
November 24, 2017; 4:35 PM
Hello

HI2
November 24, 2017; 4:37PM
Hello2

**Actual Output:**

- View announcement link not working.

**Comment by ghost** [comment]
Fixed
