### ISSUE TITLE
[Change Password] Remove alert boxes, keep onblur when constraints are violated

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#68]
![remove alert boxes](https://user-images.githubusercontent.com/25079774/34012862-56231d8a-e150-11e7-8ba2-7480730fc766.gif)

All change passwords constraints are fine now, however, please remove the alert dialogs because the onblur messages are enough to inform the user of their incorrect inputs

**Comment by ericembestro** [comment]
This has been changed before I checked this. Please re-evaluate. Thanks

**Comment by Dagtwice** [comment]
![image](https://user-images.githubusercontent.com/25523187/34019590-b20f94ba-e16a-11e7-8e8f-93dd8f368d8b.png)

- Retested the issue.
-Overlapping messages/prompts.


![11](https://user-images.githubusercontent.com/25523187/34020100-47ff2e66-e16d-11e7-813b-32b17fd61e22.gif)

- Inputs were
**Current Password:** P@ssword (Incorrect)
**New Password:**  P@ssword2 (Valid)
**Confirm New Password:**  P@ssword (Mismatch)

**Comment by ericembestro** [comment]
Did a fix for this. Please re-evaluate. Thanks
