### ISSUE TITLE
[View announcement] Logo is not working when clicked.

### ISSUE THREAD

**Issue by Dagtwice** [AlexAgnoII/SOFENGG#69]
![12](https://user-images.githubusercontent.com/25523187/34039131-6c14912c-e1c9-11e7-836b-36728ef067ba.gif)

**QA ERROR REPORT ID 6.3.2**
**Test ID:**6.3.2
**Tested By:** Dan

**Date Tested:**
12-15-17
6:47 PM
**Test Case Description:**  

- Clicking the logo to get back to homepage to be able to view announcements.

**Steps to reproduce error**

- Login as a student.
- Go to “Profile” from the menu.
- Click the logo to go back to the homepage.

**Expected Output:**

- All announcements with the title, date and time posted, and the description are listed in the page. 

HI2
December 15, 2017; 6:42PM
Hello2

HI
December 15, 2017; 6:42PM
Hello

**Actual Output:**

- Clicking the logo to go back to the homepage is not working.

**Comment by ghost** [comment]
Fixed
