### ISSUE TITLE
[Sign up, Log In, Edit Profile] Inform the user about the errors in their input

### ISSUE THREAD

**Issue by claudesedillo** [AlexAgnoII/SOFENGG#8]
**Tested By**: Claude

**Date Tested**: 10-18-17 12:08 AM

**Test Case Summary**: System did not notify the student that their e-mail was invalid in the registration page

**Test Case Details**: In the registration page, student typed “asd” as their e-mail. The system detected that this was an invalid email but did not inform the user

**Steps to reproduce error**

- Sign up
- Enter valid credentials
- Enter “asd” on e-mail field
- Submit

**Expected Output**: System should display an error, telling the student that their e-mail was invalid

**Actual Output**: System did not allow user to proceed with sign up but did not tell the user what was wrong, page is refreshed

**Suggested Solution**: Inform the users through the GUI when something is wrong with their inputs.

**Comment by ericembestro** [comment]
Can you re-evaluate this? Thanks

**Comment by ericembestro** [comment]
Please re-evaluate this due to finished issues. Thanks
